typography_spectrum: 0.13445793837308884
color:
  brandStrength: 0.3071774516720325
  lightness: 0.3965200565289706
  saturation: 0.24802130833268166
  rhythmicContrast: 0.8440133591648191
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.9464845922775567
name: NGNM
title: ''
description: no gods.  no masters.
